### ISSUE TITLE
FingerprintAssetsManager: Fingerprint not initialised

### ISSUE THREAD

**Issue by MBontekoning** [JesusM/FingerprintManager#2]
Hi,

Nice library, very convenient. I am using the encrypt/decrypt combination. However, when I want to initialize the decrypt listener, I immediately get `FingerprintAssetsManager: Fingerprint not initialised` without any additional feedback.

I am using the library inside a fragment and I tried `fingerprintManager = new JFingerprintManager(getContext(), "key");` on both the onCreate of the fragment and the parent activity.

Any ideas what the issue could be?

**Comment by MBontekoning** [comment]
I think the issue is the function `KeyStoreManager.isCipherAvailable()` which only checks if a defaultCipher is set, while `initCipherForDecryption()` is called, see below. Any way to quickfix this?
```
    public boolean isCipherAvailable() {
        return defaultCipher != null;
    }
```

**Comment by MBontekoning** [comment]
I think line `KeyStoreManager:91` should be changed from:
`Cipher cipher = createCipher();`
to
`defaultCipher = createCipher();`

as you do in `KeyStoreManager:62`.

**Comment by JesusM** [comment]
Hi @MBontekoning , let me ask you a few questions just to clarify what's the problem.

Unless I'm missing something, you are trying to encrypt/decrypt using the library. Also, it seems you are using two instances of the library, one in your fragment and another one in its parent activity. Am I right?

If so, I think what's the problem, so expect a fix soon. Thanks for the catch.

**Comment by JesusM** [comment]
@MBontekoning I've created #3 in order to fix the issue you identified. Do you mind checking if it solves your issue?

**Comment by MBontekoning** [comment]
@JesusM Yes it works, perfect! Thank you for solving this so quick.
