### ISSUE TITLE
onCancelled()

### ISSUE THREAD

**Issue by MBontekoning** [JesusM/FingerprintManager#5]
Hi @JesusM,

I might be a very nice addition to have an `onCancelled()` method in `FingerprintBaseCallback`.

In my use case I am asking the user if he/she wants to set a fingerprint instead of a passcode. If the user, however, clicks cancel in the dialog, I would like to assume that the user reconsidered and skip the option of setting a fingerprint. Currently, there is no way knowing if the dialog is cancelled, right?

Again, very nice work on this library!

**Comment by JesusM** [comment]
@MBontekoning I've created #6 in order to fix this issue, could you check that it works for you?
